# Dockerfile that creates a container suitable to build dotnet-cli
FROM ubuntu:14.04
MAINTAINER Hyung-Kyu Choi <hk0110.choi@samsung.com>
ENV http_proxy "http://10.112.1.184:8080/"
ENV https_proxy "https://10.112.1.184:8080/"
 
# Essential setting (buildtools)
RUN apt-get update
RUN apt-get -qqy install \
        unzip \
        curl \
        wget
 
RUN echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" >> /etc/apt/sources.list
RUN echo "deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" >> /etc/apt/sources.list
RUN wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -
RUN apt-get update
 
# Dependencies for build CoreCLR
RUN apt-get update
RUN apt-get -qqy install \
        build-essential \
        cmake \
        llvm-3.9 \
        clang-3.9 \
        lldb-3.9 \
        lldb-3.8-dev \
        libunwind8 \
        libunwind8-dev \
        gettext \
        libicu-dev \
        liblttng-ust-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        uuid-dev
 
# Dependencies for build CoreCLR crossbuild
RUN apt-get -qqy install \
        binutils-arm-linux-gnueabihf
 
# etc.
RUN apt-get -qqy install \
        libkrb5-3 \
        liblttng-ust0 \
        libssl1.0.0 \
        zlib1g \
        libuuid1 \
        debhelper \
        devscripts \
        git
 
# Use clang as c++ compiler
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-3.9 100
RUN update-alternatives --set c++ /usr/bin/clang++-3.9
 
# Setup User to match Host User, and give superuser permissions
ARG USER_ID=0
RUN useradd -m code_executor -u ${USER_ID} -g sudo
RUN echo 'code_executor ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 
# With the User Change, we need to change permissions on these directories
RUN chmod -R a+rwx /usr/local
RUN chmod -R a+rwx /home
RUN chmod -R 755 /usr/lib/sudo
# Set user to the one we just created
USER ${USER_ID}
# Set working directory
WORKDIR /opt/code
